vaultwarden_user_name: "vaultwarden"
vaultwarden_group_name: "vaultwarden"
vaultwarden_base_path: "/opt/vaultwarden"
vaultwarden_data_path: "{{ vaultwarden_base_path }}/data"
vaultwarden_backup_path: "{{ vaultwarden_base_path }}/backups"
vaultwarden_image: "vaultwarden/server:latest"
vaultwarden_port: "127.0.0.1:8888:80"
vaultwarden_remote_backup: false
nginx_user: "{{ 'www-data' if ansible_distribution == 'Debian' else 'nginx' }}"