- hosts: pi
  remote_user: ansible
  become: yes
  roles:
    - geerlingguy.docker
    - artis3n.tailscale   
    - pi-tailscale-certs     
    - geerlingguy.nginx   
    - vaultwarden
    - geerlingguy.security
  vars: 
    tailscale_authkey: "{{ TAILSCALE_AUTH_KEY }}"
    dns_domain: "{{ VAULTWARDEN_SECONDARY_DOMAIN }}"
    vaultwarden_domain: "{{ VAULTWARDEN_SECONDARY_DOMAIN }}"
    vaultwarden_backup: false
    security_ssh_port: 22
    security_sudoers_passwordless: 
      - ansible
    security_autoupdate_enabled: true
    security_autoupdate_reboot: false
    security_fail2ban_enabled: true

- hosts: vps
  remote_user: ansible
  become: yes
  roles:
    - geerlingguy.docker
    - artis3n.tailscale 
    - geerlingguy.nginx
    - vaultwarden
    - geerlingguy.certbot        
    - geerlingguy.security  
  vars:
    tailscale_authkey: "{{ TAILSCALE_AUTH_KEY }}"
    tailscale_up_skip: true # temporarily paused due to exit node configuration issues
    certbot_install_method: package
    certbot_auto_renew: true
    certbot_auto_renew_user: "root"
    certbot_auto_renew_hour: "4"
    certbot_auto_renew_minute: "30"
    certbot_create_if_missing: true
    certbot_admin_email: "{{ ADMIN_EMAIL }}"
    certbot_create_standalone_stop_services:
      - nginx
    certbot_certs:
      - domains:
        - "{{ VAULTWARDEN_PRIMARY_DOMAIN }}"
    vaultwarden_domain: "{{ VAULTWARDEN_PRIMARY_DOMAIN }}"
    vaultwarden_backup: true
    vaultwarden_remote_backup_host: "{{ VAULTWARDEN_REMOTE_BACKUP_HOST }}"
    security_ssh_port: 22
    security_sudoers_passwordless: 
      - ansible
    security_autoupdate_enabled: true
    security_autoupdate_reboot: false
    security_fail2ban_enabled: true