---
# Install our various referenced roles
roles:
  - src: geerlingguy.repo-epel
  - src: geerlingguy.nginx
  - src: geerlingguy.certbot
  - src: geerlingguy.docker
  - src: geerlingguy.security
  - src: artis3n.tailscale

# Modules used by our custom roles (e.g. docker_container in TransparenC)
collections:
  - name: community.docker
