- name: generate tailscale certs
  command: > 
    tailscale cert
    --cert-file {{vaultwarden_cert_path}}
    --key-file {{vaultwarden_key_path}}
    {{ vaultwarden_domain }} 
  notify: restart nginx